version: "3.8"

volumes:
  db_vol:

networks:
  takwa_network:
    driver: bridge

services:
  mysqldb:
    networks:
      - takwa_network
    container_name: mysqldb
    image: mysql:5.7
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db_vol:/var/lib/mysqldb

  spring-boot-app:
    image: takwaaouichaoui/devops
    container_name: Takwaspring
    ports:
      - "8089:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/achatdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysqldb
    networks:
      - takwa_network
